### ISSUE TITLE
Annotation or label for PersistentVolumeClaim encryption?

### ISSUE THREAD

**Issue by tatupesonen** [UpCloudLtd/uks-instructions#55]
Hello! As per [this documentation](https://upcloud.com/resources/docs/storage), UpCloud now supports encryption at rest for block storage.

Is it on your roadmap to add a label or an annotation to encrypt PVCs on creation, for example like this:
```yaml
apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: example-pvc
  labels:
    upcloud.com/encrypt: "true"   
spec:  
  accessModes:  
    - ReadWriteOnce  
  resources:  
    requests:  
      storage: 10Gi
```
